spring.application.name=ecom
spring.h2.console.enabled=true
project.image=images/
spring.datasource.url=jdbc:h2:mem:dfd5887d-1516-4564-8ca0-2abb85e1b317
spring.app.jwtSecret=mySecretKey123912738nfjfjbksbseeftskhjfhsgfugkrjgurg
spring.app.jwtExpirationMs=86400000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.ecommerce.project=DEBUG
spring.ecom.app.jwtCookieName=springBootEcom
