spring.application.name=ecom
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
project.image=images/
spring.datasource.url=jdbc:h2:mem:dfd5887d-1516-4564-8ca0-2abb85e1b317
#spring.jpa.hibernate.ddl-auto=update
